jobs:
 - template: default.yml@templates
   parameters:
     minrust: 1.45.2

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.4
      endpoint: tower-rs
