[package]
name = "tokio-tower"
version = "0.1.1"
edition = "2018"

description = "Bridging the protocol gap between Tokio and Tower"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/tokio-tower"
repository = "https://github.com/jonhoo/tokio-tower.git"

keywords = ["tokio", "tower", "asynchronous", "protocol", "transport"]
categories = ["asynchronous", "network-programming"]

license = "MIT"

[features]
log = ["tokio-trace/log"]
default = ["tokio-trace"]

[dependencies]
tower-service = "0.2"
tower-load = { git = "https://github.com/tower-rs/tower.git" }
futures = "0.1"
tokio-executor = "0.1.5"
tokio-sync = "0.1"
crossbeam = "0.7"
tokio-trace = { version = "0.1", optional = true }

[dev-dependencies]
tower = "0.1"
tower-util = "0.1"
tokio = "0.1"
serde = "1.0"
serde_derive = "1.0"
async-bincode = "0.4"
slab = "0.4"
tokio-mock-task = "0.1"
