[package]
name = "tokio-tower"
version = "0.1.0"
edition = "2018"

description = "Bridging the protocol gap between Tokio and Tower"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/tokio-tower"
repository = "https://github.com/jonhoo/tokio-tower.git"

keywords = ["tokio", "tower", "asynchronous", "protocol", "transport"]
categories = ["asynchronous", "network-programming"]

license = "MIT"

[dependencies]
tower-service = "0.2"
tower-buffer = "0.1"
tower-direct-service = "0.1"
futures = "0.1"
tokio-executor = "0.1.5"

[dev-dependencies]
tokio = "0.1"
serde = "1.0"
serde_derive = "1.0"
async-bincode = "0.4"
slab = "0.4"

[patch.crates-io]
tower-service = { git = "https://github.com/tower-rs/tower.git" }
tower-direct-service = { git = "https://github.com/tower-rs/tower.git" }
tower-buffer = { git = "https://github.com/tower-rs/tower.git" }
