[package]
name = "tokio-tower"
version = "0.2.0-alpha.1"
edition = "2018"

description = "Bridging the protocol gap between Tokio and Tower"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/tokio-tower"
repository = "https://github.com/jonhoo/tokio-tower.git"

keywords = ["tokio", "tower", "asynchronous", "protocol", "transport"]
categories = ["asynchronous", "network-programming"]

license = "MIT"

[features]
log = ["tracing/log"]
default = ["tracing"]

[dependencies]
tower-service = "=0.3.0-alpha.1"
tower-load = "=0.3.0-alpha.1"
futures-util-preview = "=0.3.0-alpha.18"
futures-core-preview = "=0.3.0-alpha.18"
futures-sink-preview = "=0.3.0-alpha.18"
tokio-executor = "=0.2.0-alpha.4"
tokio-sync = "=0.2.0-alpha.4"
crossbeam = "0.7"
tracing = { version = "0.1.2", optional = true }
pin-project = "0.4.0-alpha.11"

[dev-dependencies]
tokio = "=0.2.0-alpha.4"
serde = "1.0"
serde_derive = "1.0"
async-bincode = "0.5.0-alpha.2"
slab = "0.4"
tokio-test = "=0.2.0-alpha.4"
