[package]
name = "tokio-tower"
version = "0.1.0"

description = "Bridging the protocol gap between Tokio and Tower"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/tokio-tower"
repository = "https://github.com/jonhoo/tokio-tower.git"

keywords = ["tokio", "tower", "asynchronous", "protocol", "transport"]
categories = ["asynchronous", "network-programming"]

license = "MIT/Apache-2.0"

[dependencies]
tower-service = "0.1"
tower-discover = "0.1"
tower-balance = "0.1"
futures = "0.1"
log = "0.4.1"
rand = "0.5"
tokio-timer = "0.2.4"
indexmap = "1"

[dev-dependencies]
tokio = "0.1"
serde = "1.0"
serde_derive = "1.0"
async-bincode = "0.4"
slab = "0.4"

[patch.crates-io]
tower-service = { git = "https://github.com/jonhoo/tower.git" }
tower-discover = { git = "https://github.com/jonhoo/tower.git" }
tower-balance = { git = "https://github.com/jonhoo/tower.git" }
tower-buffer = { git = "https://github.com/jonhoo/tower.git" }
